name: Ticket Watcher
on:
  schedule:
    - cron: '*/15 * * * *'  # toutes les 15 minutes
  workflow_dispatch:         # permet de le lancer manuellement

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

- name: Install deps
  run: python -m pip install --upgrade pip requests beautifulsoup4

      - name: Run checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
          EVENT_KEYWORD: "Lady Gaga"
          VENUE: "Accor Arena"
          EVENT_DATE: "2025-11-22"
          MAX_PRICE_EUR: "100"
        run: python check_tickets.py
